DELETE FROM ADDRESS;
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #1');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #2');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #3');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #4');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #5');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #6');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #7');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #8');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #9');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #10');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #11');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #12');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #13');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #14');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #15');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #16');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #17');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #18');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #19');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #20');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #21');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #22');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #23');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #24');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #25');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #26');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #27');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #28');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #29');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #30');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #31');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #32');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #33');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #34');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #35');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #36');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #37');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #38');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #39');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #40');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #41');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #42');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #43');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #44');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Paris', 'street #45');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #46');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #47');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #48');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #49');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #50');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #51');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #52');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #53');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #54');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #55');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #56');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #57');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #58');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #59');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #60');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #61');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #62');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #63');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #64');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #65');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #66');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #67');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #68');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #69');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #70');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #71');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #72');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #73');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #74');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #75');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #76');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #77');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #78');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #79');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #80');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #81');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #82');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #83');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #84');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #85');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #86');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #87');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #88');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #89');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #90');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #91');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #92');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #93');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #94');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #95');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #96');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #97');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #98');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #99');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Rome', 'street #100');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #101');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #102');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #103');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #104');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #105');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #106');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #107');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #108');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #109');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #110');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #111');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #112');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #113');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #114');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #115');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #116');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #117');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #118');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #119');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #120');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #121');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #122');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #123');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #124');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #125');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #126');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #127');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #128');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #129');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #130');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #131');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #132');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #133');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #134');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #135');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #136');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #137');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #138');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #139');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #140');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #141');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #142');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #143');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #144');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #145');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #146');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #147');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #148');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #149');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #150');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #151');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #152');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #153');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #154');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #155');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Seattle', 'street #156');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #157');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #158');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #159');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #160');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #161');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #162');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #163');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #164');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #165');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #166');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #167');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #168');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #169');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #170');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #171');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #172');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #173');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #174');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #175');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #176');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #177');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #178');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #179');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #180');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #181');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #182');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #183');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #184');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #185');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #186');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #187');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #188');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #189');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #190');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #191');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #192');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #193');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #194');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #195');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #196');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #197');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #198');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #199');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Tokyo', 'street #200');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #201');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #202');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #203');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #204');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #205');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #206');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #207');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #208');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #209');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #210');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #211');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #212');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #213');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #214');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #215');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #216');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #217');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #218');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #219');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #220');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #221');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #222');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #223');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #224');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #225');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #226');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #227');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #228');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #229');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #230');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #231');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #232');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #233');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #234');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #235');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #236');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #237');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #238');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #239');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #240');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #241');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #242');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #243');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #244');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #245');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #246');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #247');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #248');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #249');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #250');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #251');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #252');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #253');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #254');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #255');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #256');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #257');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #258');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #259');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'London', 'street #260');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #261');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #262');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #263');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #264');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #265');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #266');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #267');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #268');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #269');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #270');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #271');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #272');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #273');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #274');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #275');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #276');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #277');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #278');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #279');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #280');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #281');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #282');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #283');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #284');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #285');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #286');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #287');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #288');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #289');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #290');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #291');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #292');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #293');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #294');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #295');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #296');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #297');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #298');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #299');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Barcelona', 'street #300');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #301');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #302');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #303');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #304');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #305');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #306');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #307');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #308');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #309');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #310');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #311');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #312');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #313');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #314');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #315');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #316');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #317');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #318');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #319');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #320');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #321');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #322');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #323');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #324');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #325');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #326');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #327');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #328');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #329');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #330');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #331');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #332');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #333');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #334');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #335');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #336');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #337');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #338');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #339');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #340');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #341');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #342');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #343');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #344');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #345');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #346');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #347');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #348');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #349');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'San Francisco', 'street #350');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #351');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #352');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #353');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #354');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #355');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #356');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #357');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #358');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #359');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #360');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #361');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #362');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #363');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #364');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #365');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #366');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #367');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #368');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #369');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #370');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #371');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #372');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #373');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #374');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #375');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #376');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #377');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #378');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #379');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #380');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #381');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #382');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #383');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #384');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #385');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #386');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #387');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #388');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #389');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #390');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #391');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #392');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #393');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #394');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #395');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #396');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #397');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #398');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #399');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #400');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Toronto', 'street #401');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #402');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #403');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #404');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #405');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #406');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #407');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #408');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #409');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #410');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #411');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #412');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #413');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #414');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #415');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #416');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #417');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #418');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #419');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #420');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #421');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #422');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #423');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #424');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #425');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #426');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #427');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #428');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #429');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #430');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #431');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #432');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #433');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #434');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #435');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #436');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #437');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #438');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #439');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #440');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #441');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #442');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #443');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Delhi', 'street #444');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #445');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #446');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #447');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #448');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #449');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #450');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #451');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #452');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #453');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #454');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #455');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #456');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #457');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #458');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #459');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #460');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #461');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #462');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #463');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #464');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #465');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #466');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #467');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #468');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #469');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #470');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #471');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #472');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #473');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #474');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #475');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #476');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #477');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #478');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #479');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #480');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #481');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #482');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #483');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #484');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #485');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #486');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #487');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #488');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #489');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #490');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #491');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #492');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #493');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #494');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #495');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #496');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #497');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #498');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #499');
INSERT INTO address (id_address, city, street) VALUES (address_seq.nextval, 'Amsterdam', 'street #500');
